### ISSUE TITLE
OS recognition broken?

### ISSUE THREAD

**Issue by cwb124** [hathoward/windows_firewall#3]
Trying to run this on a Server 2012 R2 system and getting the following in the event log:

Could not retrieve catalog from remote server: Error 400 on SERVER: firewall: Kernel 'windows' is not currently supported at firewall/manifests/init.pp

**Comment by hathoward** [comment]
Thank you for opening an issue. Looks like there's some information you were trying to provide that is missing.

**Comment by cwb124** [comment]
Jumped the gun by accident.  Info added
